dir = "MSL";
author = "Wert";
hideName = 0;
hidePicture = 0;
description = "https://steamcommunity.com/id/Werthles/myworkshopfiles/";
logo = "\Werthles_MSL\data\save_ca.paa"; //mod icon when not hovered over and in editor before placing
logoOver = "\Werthles_MSL\data\saveas_ca.paa"; //mod icon when hovered over
tooltip = "Multiplayer Save and Load"; //word when mod icon hovered over
name = "Multiplayer Save and Load"; // name in expansions
picture = "\Werthles_MSL\data\save_ca.paa"; // picture in expansions
overview = "Multiplayer Save and Load<br/><br/>Save multiplayer missions in progress to finish later."; //description in expansion menu
actionName = "MSL Link"; //instead of purchase in expansions
action = "https://steamcommunity.com/id/Werthles/myworkshopfiles/"; //where WHK Link goes
tooltipOwned = "MSL Available";
//overviewPicture = "\Werthles_MSL\data\iconWHK_ca.paa";
overviewText = "MSL - Save multiplayer missions in progress to finish later.";
overviewFootnote = "inidbi2 by code34. Testing assistance from ian. Mod code by Wert(hles)";