dir = "MSL";
author = "Werthles";
hideName = 0;
hidePicture = 0;
description = "https://steamcommunity.com/id/Werthles/myworkshopfiles/";
logo = "\Werthles_MSL\data\save_ca.paa"; //mod icon when not hovered over and in editor before placing
logoOver = "\Werthles_MSL\data\saveas_ca.paa"; //mod icon when hovered over
tooltip = "Multiplayer Save/Load"; //word when mod icon hovered over
name = "Multiplayer Save/Load"; // name in expansions
picture = "\Werthles_MSL\data\save_ca.paa"; // picture in expansions
overview = "Multiplayer Save/Load<br/>Save multiplayer missions in progress to finish later.<br/>Load missions within another.<br/>Store up missions to play later."; //description in expansion menu
actionName = "MSL Link"; //instead of purchase in expansions
action = "https://steamcommunity.com/id/Werthles/myworkshopfiles/"; //where WHK Link goes
tooltipOwned = "MSL Available";
//overviewPicture = "\Werthles_MSL\data\iconWHK_ca.paa";
overviewText = "MSL - Save multiplayer missions in progress to finish later.";
overviewFootnote = "Load missions within another. Store up missions to play later.";