//DiarySetup.sqf
//All Player Machines
//Called from initPlayerLocal
//Creates Generic Diary Info

//Creates Diary Categories
player createDiarySubject ["Credits","Credits"];
player createDiarySubject ["Factions","Factions"];
player createDiarySubject ["Contacts","Leaders"];
player createDiarySubject ["HowToPlay","How To Play"];

/*
Voice of The Old Man - Johnny Castagneto           6
Voice of The Cult Elder - The Uncertain Man        7
Voice of The Investor - PlantLamp                  1
Voice of The Market Protector - Reid Granke        5
Voice of The Slave Commander - Reid Granke         2
Voice of The Rich Man - Reid Granke                8
Voice of The Mine Supervisor - PlantLamp           9
Meatball's RandomWeather2 - Meatball               3
iniDBI - code34                                    4
Tester, Advisor, Mission Helper - ian              10
Other Stuff - Werthles                             11
*/

player createDiaryRecord ["Credits",["Hired Guns 2 Credits","<font face='PuristaLight' size=20>Credits!</font><br/><br/><font color='#FFFFFF' face='PuristaLight' size=18>Voice of The Old Man - </font><font color='#FFD700' face='PuristaLight' size=18>Johnny Castagneto</font><br/><font color='#FFFFFF' face='PuristaLight' size=16>Voice of The Cult Elder - </font><font color='#FFD700' face='PuristaLight' size=18>The Uncertain Man</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Voice of The Investor - </font><font color='#FFD700' face='PuristaLight' size=18>PlantLamp</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Voice of The Market Protector - </font><font color='#FFD700' face='PuristaLight' size=18>Reid Granke</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Voice of The Slave Commander - </font><font color='#FFD700' face='PuristaLight' size=18>Reid Granke</font><br/> <font color='#FFFFFF' face='PuristaLight' size=18>Voice of The Rich Man - </font><font color='#FFD700' face='PuristaLight' size=18>Reid Granke</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Voice of The Mine Supervisor - </font><font color='#FFD700' face='PuristaLight' size=18>PlantLamp</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Meatball's RandomWeather2 - </font><font color='#FFD700' face='PuristaLight' size=18>Meatball</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>iniDBI - </font><font color='#FFD700' face='PuristaLight' size=18>code34</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Tester, Advisor, Mission Helper - </font><font color='#FFD700' face='PuristaLight' size=18>ian</font><br/><font color='#FFFFFF' face='PuristaLight' size=18>Other Stuff - </font><font color='#FFD700' face='PuristaLight' size=18>Werthles</font><br/>"]];

player createDiaryRecord ["Factions",["Militias","<font face='PuristaLight' size=18>Recent History:</font><br/><font face='PuristaLight' size=16>Armed militias used to be the only military presence on Tanoa before the CSAT invasion. Whilst these split the islands, confrontation was unusual and businesses were allowed to operate. Exploiting natural resources allowed Tanoa to build its commercial centre in the capital Georgetown.</font><br/><br/><font face='PuristaLight' size=18>Presense:</font><br/><font face='PuristaLight' size=16>- Many different groups appearing throughout Tanoa.</font>"]];

player createDiaryRecord ["Factions",["NATO","<font face='PuristaLight' size=18>Recent History:</font><br/><font face='PuristaLight' size=16>NATO have long tried to halt or hamper CSAT's territorial expansion programme. Rarely do they deploy troops to islands to defend them, such as with the western islands of Tanoa. NATO arrived there in time to prevent these islands from CSAT capture.<br/><br/>CSAT had managed to seige these islands and eliminate all NATO's overt presence.</font><br/><br/><font face='PuristaLight' size=18>Presense:</font><br/><font face='PuristaLight' size=16>- No official presence.<br/>- NATO supplies remain.</font>"]];

player createDiaryRecord ["Factions",["CSAT","<font face='PuristaLight' size=18>Recent History:</font><br/><font face='PuristaLight' size=16>CSAT invaded Tanoa 10 years ago as part of their pacific island expansion plan. They arrived with such numbers that few were prepared to fight back. CSAT have captured similar islands around the world at such a pace that their whole operation is beginning to crumble.<br/><br/>A few weeks ago, an almost complete withdrawal from Tanoa was planned, leaving only light infantry, cars and supplies, as Tanoa was thought to be very peaceful. They wanted to redeploy these troops in the more strategicly important island of Altis. But will Tanoa allow them to do so?</font><br/><br/><font face='PuristaLight' size=18>Presense:</font><br/><font face='PuristaLight' size=16>- Pockets of rebelion survivors.<br/>- Suspicion of special forces infiltration.</font>"]];

player createDiaryRecord ["Contacts",["Tanoan Narcotics - TBC","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- The drugs cartel that dominates the drugs trade.<br/>- Escorted deliveries are continualy required around the island.<br/>- Raids on deliveries are frequent.<br/>- Land, sea and air deliveries are made to make it harded for them to be intercepted.<br/>- Other operations try to steal the market share.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Vehicle delivery<br/>- Convoy Ambushes<br/>- Land, Sea and Air Combat<br/>- Enterprise</font><img image='images\Driver.jpg'/><img image='images\Captain.jpg'/><img image='images\Pilot.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Rich Man","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- Retired banker.<br/>- Owns the island.<br/>- Wants more of everything.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Sea and Land Combat<br/>- Personal Wealth</font><img image='images\Rich Man.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Market Protector","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- Shops frequently attacked by bandits.<br/>- Personal attachment to the market town.<br/>- NATO equipment is still available here.<br/>- Suspicion of support from NATO.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Infantry-Based Combat<br/>- Regional Control</font><img image='images\Protector.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Mine Supervisor","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- Hired by foreign industry to protect the operation of the mine.<br/>- Good supply of weapons to tackle any kind of threat.<br/>- Well-paid.<br/>- Frequent escorted deliveries to/from the mine are required.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Infantry/Light Vehicle-Based Combat<br/>- Enterprise</font><img image='images\Supervisor.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Slave Commander","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>Drugs are prevelant in Tanoa, and some will even give up their freedom in order to keep stay on them.<br/>- The Slave Commander 'takes care of' these people<.<br/>- Slaves operate a number of businesses in the area.<br/>- The Slave Owner lives to the north in the jungle.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Infantry-Based<br/>- Regional Conntrol</font><img image='images\commander.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Investor","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- Wants protection for his businesses around Georgetown.<br/>- Wants to expand business where possible.<br/>- Wants to fend off rival businesses.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Infantry-Based Combat<br/>- Regional Control</font><img image='images\Investor.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Cult Elder","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- Manages the cult's daily operations.<br/>- Cult used to exist throughout Tanoa.<br/>- The cult operates some local businesses.<br/>- Suspicion of envolvement in other illegal acivity.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Infantry-Based Combat<br/>- Regional Control</font><img image='images\Elder.jpg'/>"]];

player createDiaryRecord ["Contacts",["The Old Man","<font face='PuristaLight' size=18>What You Know:</font><br/><font face='PuristaLight' size=16>- Was involved with the RT Militia group before most were killed in CSAT's invasion.<br/>- Still feared and respected in the local community due to the loyalty of his followers.</font><br/><br/><font face='PuristaLight' size=18>Campaign Description:</font><br/><font face='PuristaLight' size=16>- Infantry-Based Combat<br/>- Main Campaign<br/>- Regional Control</font><img image='images\Old Man.jpg'/>"]];

player createDiaryRecord ["HowToPlay",["Progress and Saving","<font face='PuristaLight' size=16>Campaign progress is automatically saved, once you see ‘JOB COMPLETED’.<br/><br/>To save your gear:<br/>- Select 'Save Gear' on one of your weapons caches.<br/>- Disconnecting from a server will also save your gear and location.<br/>- Keep the number of different items below 100 of each of these 4 categories: Weapons, Ammo, Backpacks, Other Items, else the items may not save.<br/><br/>- To save your location:<br/>- Select 'Save Location' when approaching a leader.</font>"]];

player createDiaryRecord ["HowToPlay",["Join a Team","<font face='PuristaLight' size=18>To join a job lead by another play, they must invite you to their team. To request an invite:<br/>1. Approach a player.<br/>2. Interact by aiming at them and pressing 'U'.<br/>3. Select 'Request/Offer' a job.<br/>4. If they send you an offer to join their team, you will see this offer appear on your screen.<br/><br/></font>"]];

player createDiaryRecord ["HowToPlay",["Command a Personal Job","<font face='PuristaLight' size=18>To start a personal job:<br/>1. Press 'U' and select 'Personal Jobs'<br/>2. Select from the map the job you wish to start.<br/><br/>If the job is being completed by another player, you will instead be told whose team you need to join.<br/><br/>Joining another player's personal job is just the same as joining a leader's job, however your squad fee is paid by the job leader!</font>"]];

player createDiaryRecord ["HowToPlay",["Command a Leader's Job","<font face='PuristaLight' size=18>To start a new job from a contact:<br/>1. Approach a leader.<br/>2. Interact by aiming at them and pressing 'U'.<br/>3. Select 'Request/Offer' a job.<br/>4. Click to select between possible jobs on offer.<br/>5. Approach players or civilians in the same way, selecting 'Request/Offer Job'. If they accept your offer, they will join your team.<br/><br/></font>"]];

player createDiaryRecord ["Diary",["Signal","<font face='PuristaLight' size=16>Leader Jobs - All kinds of tasks to further the leaders' control, e.g. assaults, defences, assasinations, convoy protections/ambushes, raids, destruction etc. <br/>Personal Jobs - Steal supplies to use on other jobs.<br/><br/>Teams are only created when a job is joined. They are disbanded once jobs end.</font>"]];

player createDiaryRecord ["Diary",["Execution","<font face='PuristaLight' size=18>The Plan</font><br/><br/><font face='PuristaLight' size=16>- Visit the Tanoan leaders.<br/>- Ask them for jobs (point and press 'U').<br/>- Hire a team of players and/or civilians.<br/>- Start personal jobs (press 'U', 'Personal Jobs')<br/>- Complete other players' jobs (counts towards your game progress too!)<br/><br/>After completing 50 jobs from the Tanoan leaders, you should have enough influence to forge an alliance against a CSAT invasion. Check the TV to see if CSAT are on their way!</font>"]];

player createDiaryRecord ["Diary",["Mission","<font face='PuristaLight' size=18>Unite Tanoa Against CSAT</font><br/><br/><font face='PuristaLight' size=16>Speak to the new Tanoan leaders. Work for them to control Tanoa. When the time comes, unite them against a new CSAT invasion.</font>"]];

player createDiaryRecord ["Diary",["Situation","<font face='PuristaLight' size=24>HIRED GUNS 2 - TANOAN ANARCHY</font><br/><br/><font face='PuristaLight' size=18>Prologue</font><br/><br/><font face='PuristaLight' size=16>CSAT is not the force it once was. Trying to recapture Altis, CSAT moved most of their forces from peaceful Tanoa to Altis, following a brutal insurgent campaign.<br/><br/>But Tanoan leaders saw the chance to take Tanoa for themselves. They eliminated most of CSAT left on Tanoa.<br/><br/></font><font face='PuristaLight' size=18>Now</font><br/><br/><font face='PuristaLight' size=16>You decide to meet with those who wiped out CSAT. The only way to survive on this lawless island is to work for these new leaders or carry out secret personal jobs.<br/><br/>If CSAT ever comes back, you'll need enough support from these leaders to work together to defend Tanoa.</font>"]];